### ISSUE TITLE
Create the Players Pages

### ISSUE THREAD

**Issue by robert-damoc** [robert-damoc/game-stats#10]
Add the pages for the players (the CRUD)
Add some styles as you see fit, using Bootstrap

A link to the Players#index should be added to the navbar. Name it `Players`

**Comment by MariusTulbure** [comment]
"Add the pages for the games (the CRUD)" you mean to add the pages for players, not for games,right?

**Comment by robert-damoc** [comment]
> "Add the pages for the games (the CRUD)" you mean to add the pages for players, not for games,right?

Good catch. I updated the description.
