### ISSUE TITLE
Limit number of players in a game

### ISSUE THREAD

**Issue by robert-damoc** [robert-damoc/game-stats#34]
Add a limit to the number of players that can be in a game. I suppose the limit should be 8.

1. Add a constant in the games model, with the proper value
2. When you add players to a game, make sure that the limit isn't reached
3. In the Games List (#index), add a new, sortable column, that shows how many players out of how many are there (e.g. `5/8`)

**Comment by MariusTulbure** [comment]
this issue was included in the previous 2 isuses that i had, and it's now resolved
