### ISSUE TITLE
Add Round capability in UI

### ISSUE THREAD

**Issue by robert-damoc** [robert-damoc/game-stats#45]
From the game view, I should be able to see the list of rounds associated with the game, ordered by position.
I should also be able to create/edit/destroy the rounds individually. 

For the display, we can have a table, like:
|  | Player1 name | Player2 name |   |
|---|---|---|---|
| King ❤️  | ✅  |  |
| Queens |  | ✅   |
| Totale | ✅  |  |
| 10 ♣️ | | ✅ | |
|   |  |  |  |
|  Scores |  |  | ➕ |
|  King ❤️  |  -400 | 0  |   ✏️ 🗑️ |
|  Queens |  -100 | -300  |  ✏️ 🗑️ |  
|  Totale | -750  | -750  |    ✏️ 🗑️ |
| 10 ♣️ | 400 | 0 |  ✏️ 🗑️ |
|   |  |  |  |
| Total | -850 | -1050 |    |

**Comment by MariusTulbure** [comment]
Do you want me to remove from the UI the unnecessary tables from the game/show page that we first made?

**Comment by robert-damoc** [comment]
> Do you want me to remove from the UI the unnecessary tables from the game/show page that we first made?

Yes please
