### ISSUE TITLE
Create the Games Pages

### ISSUE THREAD

**Issue by robert-damoc** [robert-damoc/game-stats#8]
Add the pages for the games (the CRUD) (added by scaffold)
Add some styles as you see fit, using Bootstrap

Make sure the pages work with the `state` params (when you create/show/edit/etc)

For the index, display the games as a table. For now, the table will have 3 columns, in the following order: `id`, `state`, `created date`

A link to the Games#index should be added to the navbar. Name it `Games`

Include print screens in the PR after it is ready

**Comment by MariusTulbure** [comment]
on update/create I need a dropdown to choose the state
